config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :causes
  resources :do_gooders
  resources :coders
  resources :users

  get '/redirect', to: 'users#redirect', as: "redirect"

  get '/signup', to: 'welcome#signup', as: "signup"
  get '/login', to: 'welcome#login', as: 'login'
  get '/logout', to: 'welcome#logout', as: 'logout'
end

app/models/cause.rb
class Cause < ActiveRecord::Base
  has_many :causeUsers

  has_many :coders, through: :causeUsers
  has_many :do_gooders, through: :causeUsers

  validates :name, length: { minimum: 5 }

  def self.search(query)
    where("name like ?", "%#{query}%")
  end

  SKILLS = {
    :web_design => "Web Design",
    :web_development => "Web Development",
    :ios_development => "iOS Development",
    :android_development => "Android Development",
    :data_analysis => "Data Analysis",
    :algorithm_design => "Algorithm Design",
    :ruby_on_rails => "Ruby on Rails",
    :django => "Django",
    :html_css => "HTML and CSS",
    :ruby => "Ruby",
    :python => "Python",
    :javascript => "JavaScript",
    :java => "Java",
    :cpp => "C++",
    :c => "C",
  }


  def skills
    skill_array = []
    skill_array.push("Web Design") if self.web_design
    skill_array.push("Web Development") if self.web_development
    skill_array.push("iOS Development") if self.ios_development
    skill_array.push("Android Development") if self.android_development
    skill_array.push("Data Analysis") if self.data_analysis
    skill_array.push("Algorithm Design") if self.algorithm_design
    skill_array.push("Ruby on Rails") if self.ruby_on_rails
    skill_array.push("JavaScript") if self.python
    skill_array.push("Java") if self.java
    skill_array.push("C++") if self.cpp
    skill_array.push("C") if self.c
    skill_array
  end

end

app/models/cause_user.rb
class CauseUser < ActiveRecord::Base
  belongs_to :cause
  belongs_to :coder, foreign_key: :user_id
  belongs_to :do_gooder, foreign_key: :user_id
end

app/models/coder.rb
class Coder < User
  SKILLS = {
    :web_design => "Web Design",
    :web_development => "Web Development",
    :ios_development => "iOS Development",
    :android_development => "Android Development",
    :data_analysis => "Data Analysis",
    :algorithm_design => "Algorithm Design",
    :ruby_on_rails => "Ruby on Rails",
    :django => "Django",
    :html_css => "HTML and CSS",
    :ruby => "Ruby",
    :python => "Python",
    :javascript => "JavaScript",
    :java => "Java",
    :cpp => "C++",
    :c => "C",
  }


    SKILLS = {
    :web_design => "Web Design",
    :web_development => "Web Development",
    :ios_development => "iOS Development",
    :android_development => "Android Development",
    :data_analysis => "Data Analysis",
    :algorithm_design => "Algorithm Design",
    :ruby_on_rails => "Ruby on Rails",
    :django => "Django",
    :html_css => "HTML and CSS",
    :ruby => "Ruby",
    :python => "Python",
    :javascript => "JavaScript",
    :java => "Java",
    :cpp => "C++",
    :c => "C",
  }

  def skills
    skill_array = []
    skill_array.push("Web Design") if self.web_design
    skill_array.push("Web Development") if self.web_development
    skill_array.push("iOS Development") if self.ios_development
    skill_array.push("Android Development") if self.android_development
    skill_array.push("Data Analysis") if self.data_analysis
    skill_array.push("Algorithm Design") if self.algorithm_design
    skill_array.push("Ruby on Rails") if self.ruby_on_rails
    skill_array.push("JavaScript") if self.python
    skill_array.push("Java") if self.java
    skill_array.push("C++") if self.cpp
    skill_array.push("C") if self.c
    skill_array
  end


end

app/models/do_gooder.rb
class DoGooder < User
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :causeUsers
  has_many :causes, through: :causeUsers

  validates :name, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 8 }

  has_secure_password
  validates_confirmation_of :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base	
  protect_from_forgery with: :exception
end

app/controllers/causes_controller.rb
class CausesController < ApplicationController

  def index
    if params[:search]
      @causes = Cause.search(params[:search]).order("created_at DESC")
    else
      @causes = Cause.order("created_at DESC")
    end
  end

  def new
    @cause = Cause.new
    render action: 'new', layout: false
  end

  def create
  end

  def edit
  end

  def update
  end

  def show
    @cause = Cause.find(params[:id])
  end

  def destroy
  end

  private

  def coder_params
    params.require(:coder).permit(:name, :description, :picture, :help_needed)
  end
end

app/controllers/coders_controller.rb
class CodersController < ApplicationController
  def index
  end

  def new
    @coder = Coder.new
  end

  def create
    @coder = Coder.new(coder_params)

    if @coder.save
      session[:id] = @coder.id
      params[:id] = @coder.id
      redirect_to @coder
    else
      redirect_to :back
    end

  end


  def show
    @coder = Coder.find(params[:id])
    @current_user = @coder
  end

  private

  def coder_params
    params.require(:coder).permit(:name, :email, :picture, :title, :password, :password_confirmation)
  end
end

app/controllers/do_gooders_controller.rb
class DoGoodersController < ApplicationController
  def index
  end

  def new
    @do_gooder = DoGooder.new
  end

  def create
    @do_gooder = DoGooder.new(do_gooder_params)

    if @do_gooder.save
      session[:id] = @do_gooder.id
      params[:id] = @do_gooder.id
      redirect_to @do_gooder
    else
      redirect_to :back
    end

  end

  def show
    @do_gooder = DoGooder.find(params[:id])
    @current_user = @do_gooder
  end

  private

  def do_gooder_params
    params.require(:do_gooder).permit(:name, :email, :picture, :title, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def redirect
    @user = User.find_by_email(params[:email])
    # user exists
    if  @user && @user.authenticate(params[:password])
      session[:id] = @user.id
      if @user.type == "Coder"
        redirect_to coder_path(@user)
      else
        redirect_to do_gooder_path(@user)
      end
    else # user doesn't exist
      redirect_to :back
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @causes = Cause.take(5)
  end

  def signup
    @coder = Coder.new
    @do_gooder = DoGooder.new
  end

  def login
  end

  def logout
    session[:id] = nil

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/causes/index.html.erb
<% @causes.each do |cause| %>
  <div class="cause">
		<img src="http://www.customspeedsuits.com/images/art/2010_09_35/ribbon-for-a-cause_995_thumb.jpg">
    <h1 class="cause-name"><%= link_to cause.name, cause %></h1>
    <p class="cause-content"><%= cause.description %></p>
    <p class="cause-content"><%= cause.help_needed %></p>
  </div>
<% end %>

app/views/causes/new.html.erb
<div>
  <%= form_for(@cause) do |f| %>
  <ul>
    <%= f.label :name %><br>
    <%= f.text_area :name, required: true %>
  </ul>
  <ul>
    <%= f.label :description %><br>
    <%= f.text_area :description, required: true %>
  </ul>
  <ul>
    <% Cause::SKILLS.each do |skill, skill_string| %>
      <li>
        <%= check_box_tag(skill) %>
        <%= label_tag(skill, skill_string) %>
      </li>
    <% end %>
  </ul>
  <ul>
    <%= f.submit "Create Cause" %>
  </ul>
  <% end %>
</div>

app/views/causes/show.html.erb
<h3><%= @cause.name %></h3>
<br/><br/>
<h3><%= @cause.description %></h3>
<br/><br/>
<h3><%= @cause.help_needed %></h3>

<div>
  SKILLS NEEDED:<br/>
  <% @cause.skills.each do |skill| %>
    <%= skill %><br/>
  <% end %>
</div>

app/views/coders/new.html.erb
<div>
  <%= form_for(@coder) do |f| %>
  <ul>
    <%= f.label :name %><br>
    <%= f.text_area :name, required: true %>
  </ul>
  <ul>
    <%= f.label :about %><br>
    <%= f.text_area :about, required: true %>
  </ul>
  <ul>
    <% Coder::SKILLS.each do |skill, skill_string| %>
      <li>
        <%= check_box_tag(skill) %>
        <%= label_tag(skill, skill_string) %>
      </li>
    <% end %>
  </ul>
  <ul>
    <%= f.submit "Create Profile" %>
  </ul>
  <% end %>
</div>

app/views/coders/show.html.erb
<h3><%= @coder.name %></h3>

<%= @coder.about %><br/><br/>

<div>
  MY SKILLS:<br/>
  <% @coder.skills.each do |skill| %>
    <%= skill %><br/>
  <% end %>
</div>

<br/><br/>

<div>
  MY CAUSES:<br/>
  <% @coder.causes.each do |cause| %>
    <%= cause.name %><br/>
    <%= cause.description %><br/>
  <% end %>
</div>

<br/><br/>

<div>
  CONTACT:<br/>
  <%= @coder.email %>
</div>

<button><%= link_to 'Edit Your Profile', edit_coder_path %></button>

app/views/do_gooders/show.html.erb
<% if @current_user %>
  <h1>Welcome <%= @do_gooder.name.capitalize %></h1>

  <h2>About Me: <%= @do_gooder.about %></h2>

  <div>
  MY CAUSES:<br/>
  <% @do_gooder.causes.each do |cause| %>
    <%= cause.name %><br/>
    <%= cause.description %><br/>
  <% end %>
 </div>

<!-- a button goes here goes here for the action to create a new cause -->
<button class="btn btn-default" id="create-cause">CREATE A CAUSE PROFILE.</button>
<div id="cause-form"></div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>CodeCause</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<link href='http://fonts.googleapis.com/css?family=Pontano+Sans' rel='stylesheet' type='text/css'>
</head>
<body>
	<div class="navbar navbar-default">
		<div class="container" id="navbar-container">
			<ul class="nav navbar-nav">
				<li class="navbar-item"><a id="logo" href="#">Code + Cause</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li>
					<%= form_tag(causes_path, method: :get, class: "navbar-form navbar-left", role:'search') do %>
					<div class="form-group input-append">
						<%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Causes" %>
						<button type="submit" class="btn btn-default">Submit</button>
					</div>
					<% end %>
				</li>
				<li class="navbar-item"><%= link_to 'Sign Up', signup_path %></li>
				<li class="navbar-item"><%= link_to 'Log In', login_path %></li>
			</ul>
		</div>
	</div>	

	<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div id="home" class="bg_parallax" data-type="background" data-speed="10">
	<div class="intro">
		<h1>Donate your dev skills to an outstanding cause.</h1><br>
		<em><h3>Organizations with a cause and charitable coders Sign-up <a href="<%= signup_path %>">Here.</a></h3></em>
	</div>
</div>

<div id="about" class="bg_parallax" data-type="background" data-speed="40">
	<h1>How It Works</h1>
	<div class="about-content">
		<p>Code Cause links more and less technical do-gooders. Coders can find causes that have been submitted by non-profits, charitable organizations and neighborhood organizers. Coders can build up their portfolios while contributing their skills pro bono to worthy causes they care about.
			<ul>
				<li>A Do-gooder can create a “Cause Profile” that describes their project, along with a list of skills and technologies they would need their prospective Coder to have.</li>
				<li>A Coder can browse Cause Profiles and express interest in a cause.</li>
				<li>Once a Coder has expressed interest in a cause, the do-gooder is then able to view the coder's profile and contact information.</li>
			</ul>
			Start searching causes now!
		</p>
	</div>
</div>

app/views/welcome/login.html.erb
<h3>Log In</h3>
<%= form_tag('/redirect', method: "get") do %>
	<%= label_tag(:email, "Email:") %>
	<%= text_field_tag(:email) %>
	<%= label_tag(:password, "Password:") %>
	<%= password_field_tag(:password) %>
	<%= submit_tag("Submit") %>
<% end %>

app/views/welcome/signup.html.erb
<!--  -->
<h4>Sign Up as a Coder</h4>
<%= form_for @coder, { action: "create" } do |f| %>
	<%= f.text_field :name, placeholder: "Name", required: true %>
	<br>
	<%= f.text_field :email, placeholder: "Email", required: true %>
	<br>
	<%= f.text_field :picture, placeholder: "Image Link" %>
	<br>
	<%= f.password_field :password, placeholder: "Password", required: true %>
	<br>
	<%= f.password_field :password_confirmation, placeholder: "Re-type Password", required: true %>
	<%= hidden_field_tag 'title', 'coder' %>
	<%= f.submit 'submit' %>
<% end %>

<!--  -->
<h4>Sign Up as a Do-Gooder</h4>
<%= form_for @do_gooder, {action: "create"} do |f| %>
	<%= f.text_field :name, placeholder: "Name", required: true %>
	<br>
	<%= f.text_field :email, placeholder: "Email", required: true %>
	<br>
	<%= f.text_field :picture, placeholder: "Image Link" %>
	<br>
	<%= f.password_field :password, placeholder: "Password", required: true %>
	<br>
	<%= f.password_field :password_confirmation, placeholder: "Re-type Password", required: true %>
	<%= hidden_field_tag 'title', 'do-gooder' %>
	<%= f.submit 'submit' %>
<% end %>